#!/usr/bin/bash

function build_release() {
    scons platform=windows target=template_release -j14
}


function build_debug() {
    local cdb=no
    if [[ "$1" == "db" ]]
    then
        echo "generating compile commands json"
        cdb=yes
    fi
    scons -j14 platform=windows arch=x86_64 target=template_debug debug_symbols=yes compiledb="${cdb}"
}

if [[ "$1" == "release" ]]
then
    echo "building release"
    build_release
elif [[ "$1" == "editor" ]]
then
    echo "building editor"
    scons -j14 platform=windows arch=x86_64 target=editor debug_symbols=yes
else
    echo "building debug"
    build_debug $1
fi

