#!/usr/bin/bash

echo "cleaning target=template_debug"
scons target=template_debug --clean
echo "cleaning target=editor"
scons target=editor --clean
echo "cleaning target=template_release"
scons target=template_release --clean
echo "removing .pdb files"
rm ./*.pdb
rm godot-cpp/*.pdb
rm cl-trading/bin/*.pdb
